"""Initial migration

Revision ID: 1082aba1e0b1
Revises: 
Create Date: 2024-09-20 18:19:09.825022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1082aba1e0b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorys', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
