"""Initial migration2

Revision ID: 766b4f937cfb
Revises: 1082aba1e0b1
Create Date: 2024-09-20 19:10:36.352111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766b4f937cfb'
down_revision = '1082aba1e0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorys', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
