"""Initial migrations add topic

Revision ID: ba25444d2f81
Revises: 426e9bec0bba
Create Date: 2024-10-01 21:33:36.119144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba25444d2f81'
down_revision = '426e9bec0bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_topic_name_category', ['name', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('uq_topic_name_category', type_='unique')

    # ### end Alembic commands ###
