"""Initial migrations add verify

Revision ID: ddf12d1f5b1c
Revises: 914b070a4740
Create Date: 2024-10-03 15:57:37.409898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf12d1f5b1c'
down_revision = '914b070a4740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expires', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['verification_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('verification_code_expires')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
