"""Initial migrations add verify

Revision ID: f18c6d8cca6d
Revises: ddf12d1f5b1c
Create Date: 2024-10-04 20:57:07.971840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f18c6d8cca6d'
down_revision = 'ddf12d1f5b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_verification_code_key', type_='unique')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('verification_code_expires')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_verification_code_key', ['verification_code'])

    # ### end Alembic commands ###
